/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Fields
         * @description List the agricultural fields, each with its name, area in hectares and boundary.
         */
        get: operations["list_fields"];
        put?: never;
        /**
         * Create Field
         * @description Create an agricultural field from a name and a GeoJSON polygon boundary.
         *
         *     The boundary is normally drawn on the map or imported rather than typed.
         */
        post: operations["create_field"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/{field_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Field
         * @description Return one agricultural field's name, area in hectares and boundary.
         *
         *     Identify the field by field_id from list_fields, which is also how a field named by the
         *     operator is resolved.
         */
        get: operations["get_field"];
        put?: never;
        post?: never;
        /**
         * Delete Field
         * @description Delete a field permanently. Identify it by field_id from list_fields.
         */
        delete: operations["delete_field"];
        options?: never;
        head?: never;
        /**
         * Update Field
         * @description Change a field's name, notes, or boundary. Identify it by field_id from list_fields.
         */
        patch: operations["update_field"];
        trace?: never;
    };
    "/api/v1/robots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Robots
         * @description List every robot in the fleet with its live status, battery, connectivity and position.
         *
         *     Status is one of offline, charging, active or idle. Use this to answer questions about the
         *     whole fleet; prefer get_robot when a single robot id is already known.
         */
        get: operations["list_robots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/robots/{robot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Robot
         * @description Return one robot's live status, battery, connectivity and position by its id.
         */
        get: operations["get_robot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Missions
         * @description List missions newest first, each with its lifecycle status and assigned robot.
         *
         *     Status is one of DRAFT, ASSIGNED, DISPATCHED, RUNNING, PAUSED, SUCCEEDED, FAILED or
         *     CANCELLED. Optionally filter by robot, by name, or both. This returns mission definitions and
         *     status, not live per-stage progress: use get_mission_state for that.
         */
        get: operations["list_missions"];
        put?: never;
        /**
         * Create Mission
         * @description Create a mission from a name and an ordered list of navigation stages.
         *
         *     Every waypoint must be a coordinate the operator stated. Do not compute one: not from a field
         *     or site boundary, not from a robot's current position, and not by converting a distance in
         *     metres into degrees. If you were given an area, a row spacing or a bearing rather than
         *     coordinates, do not call this; say you cannot work them out and ask for them.
         *
         *     ``stages`` is a list of stage objects, not text containing a list.
         *
         *     The backend assigns the mission and stage ids. The mission is created as a draft and is not
         *     dispatched.
         */
        post: operations["create_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mission
         * @description Return one mission's definition, lifecycle status and assigned robot.
         *
         *     Identify the mission by mission_id from list_missions, which is also how a mission named by
         *     the operator is resolved.
         */
        get: operations["get_mission"];
        put?: never;
        post?: never;
        /**
         * Delete Mission
         * @description Delete a mission permanently.
         *
         *     Only a draft or already-finished mission can be deleted, and this cannot be undone. Identify
         *     the mission by mission_id from list_missions.
         */
        delete: operations["delete_mission"];
        options?: never;
        head?: never;
        /**
         * Update Mission
         * @description Change a draft mission's name, description, or stages.
         *
         *     Only a mission still in DRAFT can be updated. Identify it by mission_id from list_missions.
         *     Supplying stages replaces the existing ones.
         */
        patch: operations["update_mission"];
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mission State
         * @description Return live per-stage progress for one mission, with errors attributed per stage.
         *
         *     Each stage carries a status and a progress fraction. Use this to answer how far along a
         *     mission is, or why it failed. Identify the mission by mission_id from list_missions.
         */
        get: operations["get_mission_state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign Mission
         * @description Assign a mission to a robot, readying it for dispatch without starting it.
         *
         *     Identify the mission by mission_id and give the robot_id. To also start it, use
         *     dispatch_mission instead.
         */
        post: operations["assign_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/unassign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unassign Mission
         * @description Remove the robot assignment from a mission that has not yet been dispatched.
         *
         *     Identify the mission by mission_id.
         */
        post: operations["unassign_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dispatch Mission
         * @description Dispatch a mission to a robot and start it driving.
         *
         *     Sends the mission to its assigned robot, or to ``robot_id`` when given, and begins execution.
         *     The mission must be in DRAFT or ASSIGNED; identify it by ``mission_id`` from list_missions.
         */
        post: operations["dispatch_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Mission
         * @description Cancel a mission, stopping the robot if it is running.
         *
         *     Identify it by mission_id from list_missions.
         */
        post: operations["cancel_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Mission
         * @description Pause a running mission, holding the robot in place.
         *
         *     Identify the mission by mission_id. Use resume_mission to continue it.
         */
        post: operations["pause_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Mission
         * @description Resume a paused mission, letting the robot continue.
         *
         *     Identify it by mission_id.
         */
        post: operations["resume_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Mission
         * @description Return a failed or cancelled mission to draft so it can be edited and dispatched again.
         *
         *     Identify the mission by mission_id.
         */
        post: operations["reset_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sites
         * @description List the sites, each a named local frame with its anchor position and map reference.
         */
        get: operations["list_sites"];
        put?: never;
        /**
         * Create Site
         * @description Create a site: a named local frame anchored at a GNSS position with a Nav2 map reference.
         */
        post: operations["create_site"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Site
         * @description Return one site's name, anchor position and map reference by its id.
         */
        get: operations["get_site"];
        put?: never;
        post?: never;
        /**
         * Delete Site
         * @description Delete a site. Fails if any mission still references it. Identify it by site_id.
         */
        delete: operations["delete_site"];
        options?: never;
        head?: never;
        /**
         * Update Site
         * @description Change a site's name, anchor position, or map reference. Identify it by site_id.
         */
        patch: operations["update_site"];
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Run one assistant turn and stream it as a Vercel AI UI message stream.
         *
         *     The caller owns the conversation and sends the whole history every turn; no transcript is
         *     stored, so there is nothing to restore from this side.
         *
         *     Proposed actions never execute on their own: they arrive as tool-approval chunks and pause the
         *     turn, and the caller returns a decision with the next request. A decision takes effect only
         *     where it matches a proposal this server recorded, and only once, so resending one or changing
         *     the action it names actuates nothing.
         */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Battery */
        Battery: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Battery Pct */
            battery_pct: number;
            /** Charging */
            charging: boolean;
        };
        /**
         * ErrorOrigin
         * @description Source of a mission error: the robot's execution, or a backend-authored cause.
         * @enum {string}
         */
        ErrorOrigin: "robot" | "backend";
        /**
         * ErrorReference
         * @description Key/value pair attaching context to a :class:`MissionError`.
         */
        ErrorReference: {
            /** Key */
            key: string;
            /** Value */
            value: string;
        };
        /**
         * ErrorSeverity
         * @description Severity of an error reported by the robot.
         * @enum {string}
         */
        ErrorSeverity: "WARNING" | "FATAL";
        /** FieldCreate */
        FieldCreate: {
            /** Name */
            name: string;
            geometry: components["schemas"]["Polygon"];
            /** Notes */
            notes?: string | null;
        };
        /** FieldUpdate */
        FieldUpdate: {
            /** Name */
            name?: string | null;
            geometry?: components["schemas"]["Polygon"] | null;
            /** Notes */
            notes?: string | null;
        };
        /** FieldView */
        FieldView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            geometry: components["schemas"]["Polygon"];
            /** Area Ha */
            area_ha: number | null;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Metadata */
        Metadata: {
            /** Id */
            id: string;
        } & {
            [key: string]: unknown;
        };
        /** MissionAssignBody */
        MissionAssignBody: {
            /** Robot Id */
            robot_id: string;
        };
        /** MissionCreate */
        MissionCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Stages */
            stages: components["schemas"]["NavigationStageInput"][];
        };
        /** MissionDispatchBody */
        MissionDispatchBody: {
            /** Robot Id */
            robot_id: string;
        };
        /**
         * MissionError
         * @description A structured error report attached to a stage or mission.
         *
         *     Mirrors the proto ``Error`` (severity / type / references / description); ``origin``
         *     is a backend-only marker distinguishing a robot fault from a backend-authored cause.
         */
        MissionError: {
            origin: components["schemas"]["ErrorOrigin"];
            severity: components["schemas"]["ErrorSeverity"];
            /**
             * Type
             * @description Stable identifier for programmatic dispatch (e.g. ``boundary_anchor_mismatch``).
             */
            type: string;
            /** References */
            references?: components["schemas"]["ErrorReference"][];
            /** Description */
            description: string;
        };
        /**
         * MissionStateView
         * @description A mission's per-stage state as one read shape for both REST and the live WS frame.
         */
        MissionStateView: {
            /**
             * Mission Id
             * Format: uuid
             */
            mission_id: string;
            /** Stage States */
            stage_states: components["schemas"]["StageStateView"][];
        };
        /**
         * MissionStatus
         * @description Lifecycle state of a Mission as tracked by the backend.
         * @enum {string}
         */
        MissionStatus: "DRAFT" | "ASSIGNED" | "DISPATCHED" | "RUNNING" | "PAUSED" | "SUCCEEDED" | "FAILED" | "CANCELLED";
        /** MissionUpdate */
        MissionUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Stages */
            stages?: components["schemas"]["NavigationStageInput"][] | null;
        };
        /** MissionView */
        MissionView: {
            /**
             * Mission Id
             * Format: uuid
             */
            mission_id: string;
            /** Update Id */
            update_id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Stages */
            stages: components["schemas"]["NavigationStage"][];
            status: components["schemas"]["MissionStatus"];
            /** Robot Id */
            robot_id: string | null;
            /** Dispatched At */
            dispatched_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Failure Errors */
            failure_errors?: components["schemas"]["MissionError"][] | null;
        };
        /**
         * NavigationStage
         * @description Drive the robot through an ordered list of waypoints.
         */
        NavigationStage: {
            /**
             * Stage Id
             * Format: uuid
             */
            stage_id: string;
            /**
             * On Cancel
             * @description Cleanup stages executed sequentially when this stage is cancelled. Cleanup stages are themselves non-cancellable.
             */
            on_cancel?: components["schemas"]["NavigationStage"][] | null;
            /**
             * Kind
             * @default navigation
             * @constant
             */
            kind: "navigation";
            /**
             * Waypoints
             * @description Ordered waypoints to traverse. All waypoints in one stage must share their ``kind`` (homogeneity); this is enforced by the backend at dispatch, not by this schema.
             */
            waypoints: (components["schemas"]["WGS84Waypoint"] | components["schemas"]["SiteLocalWaypoint"])[];
        };
        /**
         * NavigationStageInput
         * @description Drive the robot through an ordered list of waypoints, as requested by a caller.
         *
         *     Identity is deliberately absent, and that is the point: ``stage_id`` is assigned by the
         *     backend, so no caller can choose one. Two stages sharing an id would collapse onto a single
         *     ``mission_stage_state`` row, leaving the robot's per-stage reports unattributable.
         */
        NavigationStageInput: {
            /**
             * Kind
             * @default navigation
             * @constant
             */
            kind: "navigation";
            /**
             * Waypoints
             * @description Ordered waypoints to traverse. All waypoints in one stage must share their ``kind`` (homogeneity); this is enforced by the backend at dispatch, not by this schema.
             */
            waypoints: (components["schemas"]["WGS84Waypoint"] | components["schemas"]["SiteLocalWaypoint"])[];
            /**
             * On Cancel
             * @description Cleanup stages executed sequentially when this stage is cancelled. Cleanup stages are themselves non-cancellable.
             */
            on_cancel?: components["schemas"]["NavigationStageInput"][] | null;
        };
        /**
         * Polygon
         * @description Polygon Model
         */
        Polygon: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * Type
             * @constant
             */
            type: "Polygon";
            /** Coordinates */
            coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[][];
        };
        /** Pose */
        Pose: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * Frame
             * @default wgs84
             * @constant
             */
            frame: "wgs84";
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Heading Deg */
            heading_deg?: number | null;
            /** Horizontal Accuracy M */
            horizontal_accuracy_m?: number | null;
        };
        Position2D: [
            number,
            number
        ];
        Position3D: [
            number,
            number,
            number
        ];
        /**
         * RobotStatus
         * @description Displayed operational status of a robot.
         * @enum {string}
         */
        RobotStatus: "offline" | "charging" | "active" | "idle";
        /** RobotView */
        RobotView: {
            /** Id */
            id: string;
            metadata: components["schemas"]["Metadata"];
            /** Online */
            online: boolean;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            pose?: components["schemas"]["Pose"] | null;
            battery?: components["schemas"]["Battery"] | null;
            status: components["schemas"]["RobotStatus"];
        };
        /** SiteCreate */
        SiteCreate: {
            /** Name */
            name: string;
            /** Anchor Lat */
            anchor_lat: number;
            /** Anchor Lon */
            anchor_lon: number;
            /** Anchor Heading Deg */
            anchor_heading_deg: number;
            /** Nav2 Map Ref */
            nav2_map_ref: string;
            outline?: components["schemas"]["Polygon"] | null;
            /** Description */
            description?: string | null;
        };
        /**
         * SiteLocalWaypoint
         * @description A waypoint expressed in a Site's local Cartesian frame.
         */
        SiteLocalWaypoint: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "site_local";
            /**
             * Site Id
             * Format: uuid
             * @description Identifies the Site whose local frame this waypoint uses.
             */
            site_id: string;
            /**
             * X
             * @description Meters along the site's local +x axis.
             */
            x: number;
            /**
             * Y
             * @description Meters along the site's local +y axis.
             */
            y: number;
            /**
             * Theta
             * @description Target robot heading in radians, CCW from the site's local +x axis.
             */
            theta?: number | null;
        };
        /** SiteUpdate */
        SiteUpdate: {
            /** Name */
            name?: string | null;
            /** Anchor Lat */
            anchor_lat?: number | null;
            /** Anchor Lon */
            anchor_lon?: number | null;
            /** Anchor Heading Deg */
            anchor_heading_deg?: number | null;
            /** Nav2 Map Ref */
            nav2_map_ref?: string | null;
            outline?: components["schemas"]["Polygon"] | null;
            /** Description */
            description?: string | null;
        };
        /** SiteView */
        SiteView: {
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Name */
            name: string;
            /** Anchor Lat */
            anchor_lat: number;
            /** Anchor Lon */
            anchor_lon: number;
            /** Anchor Heading Deg */
            anchor_heading_deg: number;
            /** Nav2 Map Ref */
            nav2_map_ref: string;
            outline: components["schemas"]["Polygon"] | null;
            /** Description */
            description: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * StageStateView
         * @description One stage's runtime state plus the errors attributed to it.
         */
        StageStateView: {
            /**
             * Stage Id
             * Format: uuid
             */
            stage_id: string;
            /** Stage Index */
            stage_index: number;
            status: components["schemas"]["StageStatus"];
            /** Progress */
            progress: number;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /** Result */
            result: {
                [key: string]: string;
            } | null;
            /** Errors */
            errors: components["schemas"]["MissionError"][];
        };
        /**
         * StageStatus
         * @description Canonical per-stage status, covering both robot-reported and backend-resolved values.
         *
         *     The robot reports ``WAITING`` through ``FAILED`` on the wire. ``CANCELLED`` and
         *     ``SKIPPED`` are backend-only: the robot cannot express them (it reports a cancelled
         *     goal as ``FAILED`` and never reports a stage it did not reach), so the backend assigns
         *     them when it resolves the final per-stage view at the terminal mission transition.
         *     Inbound frames carry only the wire values; the anti-corruption mapper rejects any other.
         * @enum {string}
         */
        StageStatus: "WAITING" | "INITIALIZING" | "RUNNING" | "PAUSED" | "FINISHED" | "FAILED" | "CANCELLED" | "SKIPPED";
        /** User */
        User: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WGS84Waypoint
         * @description A waypoint anchored in the WGS84 geographic frame.
         */
        WGS84Waypoint: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "wgs84";
            /**
             * Lat
             * @description Degrees latitude, WGS84.
             */
            lat: number;
            /**
             * Lon
             * @description Degrees longitude, WGS84.
             */
            lon: number;
            /**
             * Heading Deg
             * @description Target robot heading in degrees clockwise from true north (compass bearing), [0, 360).
             */
            heading_deg?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_fields: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldView"][];
                };
            };
        };
    };
    create_field: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_field: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_field: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_field: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_robots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotView"][];
                };
            };
        };
    };
    get_robot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_missions: {
        parameters: {
            query?: {
                /** @description Filter to missions assigned to this robot id. */
                robot?: string | null;
                /** @description Filter to missions with exactly this name, matched case-insensitively. */
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_mission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mission_state: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionStateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionAssignBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unassign_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispatch_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MissionDispatchBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteView"][];
                };
            };
        };
    };
    create_site: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_site: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_site: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_site: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
