/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Fields
         * @description List the agricultural fields, each with its name, area in hectares and boundary.
         */
        get: operations["list_fields"];
        put?: never;
        /**
         * Create Field
         * @description Create an agricultural field from a name and a GeoJSON polygon boundary.
         *
         *     The boundary is normally drawn on the map or imported rather than typed.
         */
        post: operations["create_field"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/{field_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Field
         * @description Return one agricultural field's name, area in hectares and boundary.
         *
         *     Identify the field by field_id from list_fields, which is also how a field named by the
         *     operator is resolved.
         */
        get: operations["get_field"];
        put?: never;
        post?: never;
        /**
         * Delete Field
         * @description Delete a field permanently. Identify it by field_id from list_fields.
         */
        delete: operations["delete_field"];
        options?: never;
        head?: never;
        /**
         * Update Field
         * @description Change a field's name, notes, or boundary. Identify it by field_id from list_fields.
         */
        patch: operations["update_field"];
        trace?: never;
    };
    "/api/v1/robots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Robots
         * @description List every robot in the fleet with its live status, battery, connectivity and position.
         *
         *     Status is one of offline, charging, active or idle. Use this to answer questions about the
         *     whole fleet; prefer get_robot when a single robot id is already known.
         */
        get: operations["list_robots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/robots/{robot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Robot
         * @description Return one robot's live status, battery, connectivity and position by its id.
         */
        get: operations["get_robot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Missions
         * @description List missions newest first, each with its latest run.
         *
         *     A mission is a definition that can be run any number of times; ``latest_run`` carries the
         *     status, robot and timings of its most recent run and is null when it has never run. Its
         *     status is one of PENDING, DISPATCHED, RUNNING, PAUSED, SUCCEEDED, FAILED, CANCELLED or
         *     REJECTED. Optionally filter by robot, by name, or both. This returns definitions, not live
         *     per-stage progress: use get_mission_state for that.
         */
        get: operations["list_missions"];
        put?: never;
        /**
         * Create Mission
         * @description Create a mission from a name and an ordered list of navigation stages.
         *
         *     Every waypoint must be a coordinate the operator stated. Do not compute one: not from a field
         *     or site boundary, not from a robot's current position, and not by converting a distance in
         *     metres into degrees. If you were given an area, a row spacing or a bearing rather than
         *     coordinates, do not call this: use plan_coverage_mission for a field that should be covered, and
         *     otherwise say you cannot work the coordinates out and ask for them.
         *
         *     ``stages`` is a list of stage objects, not text containing a list.
         *
         *     The backend assigns the mission and stage ids. The mission is a definition and is not
         *     dispatched; dispatch_mission runs it, as many times as wanted.
         */
        post: operations["create_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mission
         * @description Return one mission's definition, default robot and latest run.
         *
         *     Identify the mission by mission_id from list_missions, which is also how a mission named by
         *     the operator is resolved. Its run history is list_mission_runs.
         */
        get: operations["get_mission"];
        put?: never;
        post?: never;
        /**
         * Delete Mission
         * @description Delete a mission that never ran, or archive one that did.
         *
         *     A mission with runs is archived rather than deleted: it leaves the list, its runs stay
         *     readable, and restore_mission brings it back. A mission with a run in progress is refused.
         *     Identify the mission by mission_id from list_missions.
         */
        delete: operations["delete_mission"];
        options?: never;
        head?: never;
        /**
         * Update Mission
         * @description Change a mission's name, description, or stages.
         *
         *     Allowed at any time, even while a run is active: a run carries its own copy of the plan, so
         *     editing the definition never changes what a run did or is doing. Identify the mission by
         *     mission_id from list_missions. Supplying stages replaces the existing ones; a stage that
         *     carries its stage_id keeps its identity across the edit, one without gets a new id, and one
         *     left out is removed. A planned coverage stage is carried by its stage_id alone; its path
         *     cannot be written here, only re-planned.
         */
        patch: operations["update_mission"];
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mission State
         * @description Return live per-stage progress of the mission's current run, errors attributed per stage.
         *
         *     The current run is the most recently started one still active, else the latest run of any
         *     outcome. Each stage carries a status and a progress fraction. Use this to answer how far
         *     along a mission is, or why it failed. A mission that has never run has no state (404).
         */
        get: operations["get_mission_state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan Coverage Mission
         * @description Create a mission that covers a whole field, planned from the field's own boundary.
         *
         *     Use this whenever the operator asks to cover, survey, mow or treat a field rather than to
         *     drive to stated points. Give the field_id, the robot the plan is for, and the working width
         *     in metres; supply no coordinates, because the path is computed from the stored boundary, and
         *     no turning radius, because the robot declares its own.
         *
         *     With ``replan`` set, the named mission's plan is rewritten in place instead and its id is
         *     returned. The mission is not dispatched. Its coverage metrics come back with it, so the
         *     operator can judge the plan before dispatching it.
         */
        post: operations["plan_coverage_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Mission
         * @description Bring an archived mission back into the list. Identify it by mission_id.
         */
        post: operations["restore_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign Mission
         * @description Set the robot a mission runs on by default, checking it can, without starting it.
         *
         *     Identify the mission by mission_id and give the robot_id. To also start it, use
         *     dispatch_mission instead.
         */
        post: operations["assign_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/unassign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unassign Mission
         * @description Clear a mission's default robot. Identify the mission by mission_id.
         */
        post: operations["unassign_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dispatch Mission
         * @description Start a run of a mission on a robot.
         *
         *     Sends the mission's stages to its default robot, or to ``robot_id`` when given, and begins
         *     execution. A mission can be run any number of times; each run keeps its own record. While a
         *     run of this mission is active, a second one is refused (409). Identify the mission by
         *     ``mission_id`` from list_missions. The returned ``latest_run`` is the new run.
         */
        post: operations["dispatch_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Mission
         * @description Cancel the mission's active run, stopping the robot.
         *
         *     Identify the mission by mission_id from list_missions. With more than one run active,
         *     ``run_id`` says which. Both modes stop within seconds: 'graceful', the default, comes to a
         *     controlled stop at the next safe point and then cleans up; 'immediate' stops at once.
         */
        post: operations["cancel_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Mission
         * @description Pause the mission's running run, holding the robot in place.
         *
         *     Identify the mission by mission_id. Use resume_mission to continue it. With more than one
         *     run active, ``run_id`` says which.
         */
        post: operations["pause_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Mission
         * @description Resume the mission's paused run, letting the robot continue.
         *
         *     Identify it by mission_id. With more than one run active, ``run_id`` says which.
         */
        post: operations["resume_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Mission Runs
         * @description List a mission's runs, newest first, without their plans.
         *
         *     Every execution the mission has ever had, whatever its outcome. Each carries its own robot,
         *     timings, status and a digest of the plan it executed, so runs of an edited mission can be
         *     told apart from runs of the plan as it stands.
         */
        get: operations["list_mission_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Return one run with the plan it executed, frozen at dispatch, and its failure cause.
         */
        get: operations["get_run"];
        put?: never;
        post?: never;
        /**
         * Delete Run
         * @description Remove a finished run and its per-stage record.
         *
         *     A run still active is refused (409): its robot is driving it. The audit log keeps every
         *     completed delete; what goes is the detail.
         */
        delete: operations["delete_run"];
        options?: never;
        head?: never;
        /**
         * Annotate Run
         * @description Set or clear a run's notes. Notes are the operator's, editable at any time.
         */
        patch: operations["annotate_run"];
        trace?: never;
    };
    "/api/v1/runs/{run_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run State
         * @description Return one run's per-stage state with errors attributed per stage.
         *
         *     A run the robot has not reported on yet projects every stage as WAITING from its own plan.
         */
        get: operations["get_run_state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sites
         * @description List the sites, each a named local frame with its anchor position and map reference.
         */
        get: operations["list_sites"];
        put?: never;
        /**
         * Create Site
         * @description Create a site: a named local frame anchored at a GNSS position with a Nav2 map reference.
         */
        post: operations["create_site"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Site
         * @description Return one site's name, anchor position and map reference by its id.
         */
        get: operations["get_site"];
        put?: never;
        post?: never;
        /**
         * Delete Site
         * @description Delete a site. Fails if any mission still references it. Identify it by site_id.
         */
        delete: operations["delete_site"];
        options?: never;
        head?: never;
        /**
         * Update Site
         * @description Change a site's name, anchor position, or map reference. Identify it by site_id.
         */
        patch: operations["update_site"];
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Run one assistant turn and stream it as a Vercel AI UI message stream.
         *
         *     The caller owns the conversation and sends the whole history every turn; no transcript is
         *     stored, so there is nothing to restore from this side.
         *
         *     Proposed actions never execute on their own: they arrive as tool-approval chunks and pause the
         *     turn, and the caller returns a decision with the next request. A decision takes effect only
         *     where it matches a proposal this server recorded, and only once, so resending one or changing
         *     the action it names actuates nothing.
         */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Battery */
        Battery: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Battery Pct */
            battery_pct: number;
            /** Charging */
            charging: boolean;
        };
        /** CancelBody */
        CancelBody: {
            /** Run Id */
            run_id?: string | null;
            /**
             * @description How the robot stops. Both stop within seconds: 'graceful' comes to a controlled stop at the next safe point (the current motion completed, the implement raised) and then runs the stage's on_cancel cleanup; 'immediate' stops at once, then cleans up.
             * @default graceful
             */
            mode: components["schemas"]["CancelMode"];
        };
        /**
         * CancelMode
         * @description How the robot should react to a cancel request.
         * @enum {string}
         */
        CancelMode: "graceful" | "immediate";
        /**
         * CoverageCapability
         * @description Capabilities specific to executing COVERAGE stages.
         *
         *     A claim about steering rather than geometry: that the machine holds the swath line between
         *     its endpoints instead of taking any convenient path between them.
         */
        CoverageCapability: {
            /** Supported Waypoint Kinds */
            supported_waypoint_kinds?: components["schemas"]["WaypointKind"][];
        };
        /**
         * CoverageMetrics
         * @description What an operator needs in order to judge a plan before dispatching it.
         */
        CoverageMetrics: {
            /** Swath Count */
            swath_count: number;
            /**
             * Track Length M
             * @description Total swath length, the ground actually worked. Excludes the turns, so it is what the covered area is checked against rather than how far the machine drives.
             */
            track_length_m: number;
            /**
             * Path Length M
             * @description How far the machine drives in total, turns included.
             */
            path_length_m?: number | null;
            /** Covered Area M2 */
            covered_area_m2: number;
            /**
             * Mainland Area M2
             * @description Ground the swaths were allowed to work, which is the field less its headland. Absent on a plan plotted before it was reported.
             */
            mainland_area_m2?: number | null;
            /**
             * Max Excursion M
             * @description How far outside the boundary the driven path reaches, in metres. A turn needs a headland at least as deep as the turning radius to be contained, and fields are rarely laid out that generously, so a correct plan routinely leaves the polygon. Whether that is a manoeuvre or a collision depends on what the boundary is made of, which only the operator knows.
             */
            max_excursion_m?: number | null;
        };
        /**
         * CoverageParams
         * @description The inputs that determine a coverage path, as the planner was actually given them.
         *
         *     The turning radius reaches here from the robot's own declaration rather than from the caller,
         *     so the two cannot disagree. The working width does not: an implement is mounted per job, so
         *     only the operator knows what is on the machine today.
         */
        CoverageParams: {
            /**
             * Operation Width M
             * @description Working width of the implement, in metres.
             */
            operation_width_m: number;
            /**
             * Turning Radius M
             * @description Minimum turning radius in metres; 0 for a robot that turns on the spot.
             */
            turning_radius_m: number;
            /**
             * Headland Width M
             * @description Turning space kept inside the boundary, in metres. Records what the plan was built with, which is the robot's own turning radius unless the operator chose otherwise.
             */
            headland_width_m: number;
            /**
             * Swath Angle Deg
             * @description Bearing of the swath lines; the planner chooses one when omitted.
             */
            swath_angle_deg?: number | null;
            /**
             * Allow Overlap
             * @description Whether the last pass may overlap the one before it to cover the remainder. Absent on a plan made before it was recorded.
             */
            allow_overlap?: boolean | null;
            /**
             * Track Width M
             * @description Distance between the machine's wheels in metres, which the implement must at least span. Absent on a plan made before it was recorded.
             */
            track_width_m?: number | null;
            /**
             * Linear Curv Change
             * @description How fast curvature may change along a turn, in 1/m2. Belongs to the machine as the turning radius does. Absent on a plan made before it was recorded.
             */
            linear_curv_change?: number | null;
            /**
             * Turn Sample M
             * @description How closely a turn is sampled, in metres. A turn curves, so its shape survives only in the points taken along it. Absent on a plan made before it was recorded.
             */
            turn_sample_m?: number | null;
        };
        /**
         * CoverageProvenance
         * @description How a coverage mission came to exist.
         *
         *     Held with the mission rather than derived on demand: the field may be edited or deleted
         *     afterwards, and a generated path can only be judged, reproduced, or refused for the wrong
         *     robot against the inputs it was actually made from.
         */
        CoverageProvenance: {
            /**
             * Field Id
             * Format: uuid
             */
            field_id: string;
            /** Boundary Digest */
            boundary_digest: string;
            /** Field Area M2 */
            field_area_m2: number;
            /** @description The ground the swaths were allowed to work: the field less its headland. Held here with the rest of the geometry this plan was made against, since the field itself may be edited or deleted afterwards. Absent on a plan made before it was recorded. */
            mainland_boundary?: components["schemas"]["Polygon"] | null;
            params: components["schemas"]["CoverageParams"];
            metrics: components["schemas"]["CoverageMetrics"];
            /** Planner Version */
            planner_version: string;
            /** Planned For Robot Id */
            planned_for_robot_id: string;
            /**
             * Planned At
             * Format: date-time
             */
            planned_at: string;
        };
        /**
         * CoverageStage
         * @description Cover a field by driving its swaths in order, each reached by the turn before it.
         *
         *     Provenance is required, so this stage cannot be written by hand: swaths come from the
         *     planner, and the checks that refuse a robot which would cut the corners read the parameters
         *     the plan was made with.
         */
        CoverageStage: {
            /**
             * Stage Id
             * Format: uuid
             */
            stage_id: string;
            /**
             * On Cancel
             * @description Cleanup stages executed sequentially when this stage is cancelled. Cleanup stages are themselves non-cancellable.
             */
            on_cancel?: (components["schemas"]["NavigationStage"] | components["schemas"]["CoverageStage"])[] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "coverage";
            /**
             * Segments
             * @description The whole stage as one ordered route. Concatenating the segments gives the drivable line, turns included; the kinds say which of it is a worked swath. Consecutive segments share an endpoint, which a receiver joining them skips.
             */
            segments: components["schemas"]["Segment"][];
            /** @description The inputs, measurements and act that produced these segments. */
            provenance: components["schemas"]["CoverageProvenance"];
        };
        /**
         * CoverageStageRef
         * @description A coverage stage this mission already has, carried through an edit unchanged.
         *
         *     Swaths are a planner's output, so there is no way to write one here: the stage is named, and
         *     the stored segments and provenance are kept as they are. Naming a stage of another mission,
         *     or one that is not coverage, is refused.
         */
        CoverageStageRef: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "coverage";
            /**
             * Stage Id
             * Format: uuid
             */
            stage_id: string;
        };
        /**
         * ErrorOrigin
         * @description Source of a mission error: the robot's execution, or a backend-authored cause.
         * @enum {string}
         */
        ErrorOrigin: "robot" | "backend";
        /**
         * ErrorReference
         * @description Key/value pair attaching context to a :class:`MissionError`.
         */
        ErrorReference: {
            /** Key */
            key: string;
            /** Value */
            value: string;
        };
        /**
         * ErrorSeverity
         * @description Severity of an error reported by the robot.
         * @enum {string}
         */
        ErrorSeverity: "WARNING" | "FATAL";
        /** FieldCreate */
        FieldCreate: {
            /** Name */
            name: string;
            geometry: components["schemas"]["Polygon"];
            /** Notes */
            notes?: string | null;
        };
        /** FieldUpdate */
        FieldUpdate: {
            /** Name */
            name?: string | null;
            geometry?: components["schemas"]["Polygon"] | null;
            /** Notes */
            notes?: string | null;
        };
        /** FieldView */
        FieldView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            geometry: components["schemas"]["Polygon"];
            /** Area Ha */
            area_ha: number | null;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LastReportView
         * @description The most recent state report the robot sent for the run.
         */
        LastReportView: {
            /**
             * Received At
             * Format: date-time
             * @description When the backend received it, by its own clock.
             */
            received_at: string;
            /**
             * Header Id
             * @description The robot's report counter; later reports have higher values.
             */
            header_id: number;
            exec_status: components["schemas"]["MissionExecStatus"];
            /**
             * Robot Timestamp
             * Format: date-time
             * @description When the robot sent it, by the robot's clock.
             */
            robot_timestamp: string;
        };
        /** Metadata */
        Metadata: {
            /** Id */
            id: string;
        } & {
            [key: string]: unknown;
        };
        /** MissionAssignBody */
        MissionAssignBody: {
            /** Robot Id */
            robot_id: string;
        };
        /**
         * MissionCoverageCreate
         * @description Request a coverage mission over a stored field.
         *
         *     Deliberately flat and geometry-free: every value is a number or an id the caller already has,
         *     and the path itself comes from the field's own boundary.
         */
        MissionCoverageCreate: {
            /**
             * Field Id
             * Format: uuid
             * @description Field to cover, from list_fields.
             */
            field_id: string;
            /**
             * Robot Id
             * @description Robot the plan is computed for.
             */
            robot_id: string;
            /**
             * Name
             * @description Mission name. Defaults to the field's own name; do not ask for one.
             */
            name?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Operation Width M
             * @description Working width of the mounted implement, in metres, and the one value only the operator knows. It is not the robot's own width: an implement is usually wider than the machine carrying it, and a plan built from the machine's width covers the field in far too many passes. Never take it from a robot's declared width; ask.
             */
            operation_width_m: number;
            /**
             * Headland Width M
             * @description Turning space kept inside the field, in metres. Omit it unless the operator states one: left open, the planner uses the robot's own turning radius, which is what a turn needs to stay inside the boundary.
             */
            headland_width_m?: number | null;
            /**
             * Swath Angle Deg
             * @description Bearing of the swath lines; the planner chooses one when omitted.
             */
            swath_angle_deg?: number | null;
            /**
             * Allow Overlap
             * @description Whether the last pass may overlap the one before it. A field is rarely a whole number of passes wide; leaving the remainder unworked is the alternative. Set it false only when working ground twice is worse than missing a strip.
             * @default false
             */
            allow_overlap: boolean;
            /**
             * Replan
             * @description The id of an existing coverage stage whose path should be re-planned in place, instead of creating a new mission. Pass it when the operator wants an existing plan changed rather than a second one: a plan is re-derived rather than edited. The mission keeps its id, its name, its other stages and every run it has had; only that stage's path and provenance change.
             */
            replan?: string | null;
        };
        /** MissionCreate */
        MissionCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Stages */
            stages: (components["schemas"]["NavigationStageInput"] | components["schemas"]["CoverageStageRef"])[];
        };
        /** MissionDispatchBody */
        MissionDispatchBody: {
            /**
             * Robot Id
             * @description Robot to run on; defaults to the assigned one.
             */
            robot_id?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * MissionError
         * @description A structured error report attached to a stage or mission.
         *
         *     ``origin`` says whether the robot reported it or the backend authored it.
         */
        MissionError: {
            origin: components["schemas"]["ErrorOrigin"];
            severity: components["schemas"]["ErrorSeverity"];
            /**
             * Type
             * @description Stable identifier for programmatic dispatch (e.g. ``boundary_anchor_mismatch``).
             */
            type: string;
            /** References */
            references?: components["schemas"]["ErrorReference"][];
            /** Description */
            description: string;
        };
        /**
         * MissionExecStatus
         * @description The robot's execution status: live (RUNNING/PAUSED) or terminal.
         *
         *     Execution truth, not the mission lifecycle status (which the backend owns and
         *     derives from this). SUCCEEDED, FAILED, and CANCELLED are terminal.
         * @enum {string}
         */
        MissionExecStatus: "RUNNING" | "PAUSED" | "SUCCEEDED" | "FAILED" | "CANCELLED";
        /** MissionUpdate */
        MissionUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Stages */
            stages?: (components["schemas"]["NavigationStageInput"] | components["schemas"]["CoverageStageRef"])[] | null;
        };
        /** MissionView */
        MissionView: {
            /**
             * Mission Id
             * Format: uuid
             */
            mission_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Stages */
            stages: (components["schemas"]["NavigationStage"] | components["schemas"]["CoverageStage"])[];
            /** Assigned Robot Id */
            assigned_robot_id: string | null;
            /** Archived At */
            archived_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Stages Digest
             * @description Digest of the stages as they stand now. A run whose stages_digest matches ran the plan this mission currently holds; one that differs ran an older plan. Computed the same way as a run's, so the two are directly comparable.
             */
            stages_digest: string;
            /** @description The most recently created run; null means the mission has never run. */
            latest_run?: components["schemas"]["RunSummaryView"] | null;
            /**
             * Active Runs
             * @description Every run of this mission still occupying a robot, newest first. Whether the mission is running is this being non-empty, not the status of latest_run: a concurrent run that ends first becomes latest_run while the other still drives. With more than one entry, mission-addressed cancel, pause and resume require a run_id, and these are the candidates.
             */
            active_runs?: components["schemas"]["RunSummaryView"][];
        };
        /**
         * NavigationCapability
         * @description Capabilities specific to executing NAVIGATION stages.
         */
        NavigationCapability: {
            /** Supported Waypoint Kinds */
            supported_waypoint_kinds?: components["schemas"]["WaypointKind"][];
        };
        /**
         * NavigationStage
         * @description Drive the robot through an ordered list of waypoints.
         */
        NavigationStage: {
            /**
             * Stage Id
             * Format: uuid
             */
            stage_id: string;
            /**
             * On Cancel
             * @description Cleanup stages executed sequentially when this stage is cancelled. Cleanup stages are themselves non-cancellable.
             */
            on_cancel?: (components["schemas"]["NavigationStage"] | components["schemas"]["CoverageStage"])[] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "navigation";
            /**
             * Waypoints
             * @description Ordered waypoints to traverse. All waypoints in one stage must share their ``kind`` (homogeneity); this is enforced by the backend at dispatch, not by this schema.
             */
            waypoints: (components["schemas"]["WGS84Waypoint"] | components["schemas"]["SiteLocalWaypoint"])[];
        };
        /**
         * NavigationStageInput
         * @description Drive the robot through an ordered list of waypoints, as requested by a caller.
         *
         *     Supply ``stage_id`` to keep a stage's identity across an edit, so its runs stay comparable;
         *     omit it for a new stage and the backend assigns one. A supplied id must already belong to the
         *     mission being edited and appear once in the request.
         */
        NavigationStageInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "navigation";
            /** Stage Id */
            stage_id?: string | null;
            /**
             * Waypoints
             * @description Ordered waypoints to traverse. All waypoints in one stage must share their ``kind`` (homogeneity); this is enforced by the backend at dispatch, not by this schema.
             */
            waypoints: (components["schemas"]["WGS84Waypoint"] | components["schemas"]["SiteLocalWaypoint"])[];
            /**
             * On Cancel
             * @description Cleanup stages executed sequentially when this stage is cancelled. Cleanup stages are themselves non-cancellable.
             */
            on_cancel?: (components["schemas"]["NavigationStageInput"] | components["schemas"]["CoverageStageRef"])[] | null;
        };
        /**
         * PhysicalParameters
         * @description Fixed physical properties of the machine, declared by the robot itself.
         */
        PhysicalParameters: {
            /**
             * Track Width M
             * @description Distance between the wheels in metres, centre to centre.
             */
            track_width_m: number;
            /**
             * Min Turning Radius M
             * @description Zero declares a robot that turns on the spot.
             */
            min_turning_radius_m: number;
        };
        /**
         * Polygon
         * @description Polygon Model
         */
        Polygon: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * Type
             * @constant
             */
            type: "Polygon";
            /** Coordinates */
            coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[][];
        };
        /** Pose */
        Pose: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * Frame
             * @default wgs84
             * @constant
             */
            frame: "wgs84";
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Heading Deg */
            heading_deg?: number | null;
            /** Horizontal Accuracy M */
            horizontal_accuracy_m?: number | null;
        };
        Position2D: [
            number,
            number
        ];
        Position3D: [
            number,
            number,
            number
        ];
        /**
         * RobotFactsheet
         * @description What a robot can do, cached by the backend to pre-flight-validate dispatch.
         *
         *     A present per-kind capability (``navigation``) declares the robot supports
         *     that stage kind. ``robot_id`` is stamped from the transport key on ingest,
         *     not carried in the wire payload.
         */
        RobotFactsheet: {
            /** Robot Id */
            robot_id: string;
            navigation?: components["schemas"]["NavigationCapability"] | null;
            coverage?: components["schemas"]["CoverageCapability"] | null;
            physical_parameters?: components["schemas"]["PhysicalParameters"] | null;
        };
        /**
         * RobotStatus
         * @description Displayed operational status of a robot.
         * @enum {string}
         */
        RobotStatus: "offline" | "charging" | "active" | "idle";
        /** RobotView */
        RobotView: {
            /** Id */
            id: string;
            metadata: components["schemas"]["Metadata"];
            /** Online */
            online: boolean;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            pose?: components["schemas"]["Pose"] | null;
            battery?: components["schemas"]["Battery"] | null;
            status: components["schemas"]["RobotStatus"];
            factsheet?: components["schemas"]["RobotFactsheet"] | null;
            current_run?: components["schemas"]["RunSummaryView"] | null;
        };
        /** RunNotesPatch */
        RunNotesPatch: {
            /** Notes */
            notes?: string | null;
        };
        /** RunOriginView */
        RunOriginView: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "manual" | "agent";
            /** Actor */
            actor: string;
            /** Tool Call Id */
            tool_call_id?: string | null;
        };
        /**
         * RunSelectBody
         * @description Which run a mission-addressed command means; needed only when several are active.
         */
        RunSelectBody: {
            /** Run Id */
            run_id?: string | null;
        };
        /**
         * RunSiteAnchor
         * @description Where a site stood when a run was dispatched into it.
         *
         *     A site-local waypoint is a pair of numbers that mean nothing without the frame they are
         *     measured in, so the frame is copied into the run beside the plan. The name is copied
         *     too, so the run stays readable after the site is deleted.
         */
        RunSiteAnchor: {
            /** Name */
            name: string;
            /** Anchor Lat */
            anchor_lat: number;
            /** Anchor Lon */
            anchor_lon: number;
            /** Anchor Heading Deg */
            anchor_heading_deg: number;
        };
        /**
         * RunStateView
         * @description A run's per-stage state as one read shape for both REST and the live WS frame.
         *
         *     Carries both ids: the WS topic is keyed by mission, so a subscriber showing one run must
         *     filter frames by ``run_id``, and a list of missions indexes them by ``mission_id``.
         */
        RunStateView: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Mission Id
             * Format: uuid
             */
            mission_id: string;
            /** Stage States */
            stage_states: components["schemas"]["StageStateView"][];
        };
        /**
         * RunStatus
         * @description Lifecycle state of a MissionRun, owned by the backend.
         *
         *     ``PENDING`` is the run row committed before the robot has answered the dispatch. ``REJECTED``
         *     is kept apart from ``FAILED`` because they mean different things for the robot: a rejection
         *     means it is definitely not driving, while a timeout or a mid-run failure means it may be.
         *     ``PAUSING``, ``RESUMING`` and ``CANCELLING`` hold an operator's request until the robot's own
         *     report confirms it.
         * @enum {string}
         */
        RunStatus: "PENDING" | "DISPATCHED" | "RUNNING" | "PAUSED" | "SUCCEEDED" | "FAILED" | "CANCELLED" | "REJECTED" | "PAUSING" | "RESUMING" | "CANCELLING";
        /**
         * RunSummaryView
         * @description A run without its stages: what a list shows, and what a mission carries as ``latest_run``.
         */
        RunSummaryView: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Mission Id
             * Format: uuid
             */
            mission_id: string;
            /** Robot Id */
            robot_id: string;
            status: components["schemas"]["RunStatus"];
            /**
             * Stages Digest
             * @description Content digest of what this run was told to do, ignoring stage ids and how a stage was produced. Two runs with the same digest drove the same ground.
             */
            stages_digest: string;
            origin: components["schemas"]["RunOriginView"];
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dispatched At */
            dispatched_at: string | null;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /** @description The robot's most recent report on this run; null before the first one. */
            last_report: components["schemas"]["LastReportView"] | null;
            /**
             * Updated At
             * Format: date-time
             * @description When the backend last changed this run: a status transition or a notes edit.
             */
            updated_at: string;
        };
        /**
         * RunTransitionView
         * @description One status change of the run, in the order they happened.
         */
        RunTransitionView: {
            from_status: components["schemas"]["RunStatus"];
            to_status: components["schemas"]["RunStatus"];
            trigger: components["schemas"]["RunTrigger"];
            /**
             * At
             * Format: date-time
             */
            at: string;
            /**
             * Actor
             * @description Who caused it: the operator's request, the robot's report, or the backend.
             * @enum {string}
             */
            actor: "operator" | "robot" | "backend";
            /**
             * Acknowledged
             * @description For an operator's request: true when the robot replied that it applied it, false when it refused or did not answer; null while unknown or for other transitions.
             */
            acknowledged?: boolean | null;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * RunTrigger
         * @description A lifecycle transition trigger: the named cause of a status change.
         *
         *     The ``*_REQUEST`` triggers are the operator asking; ``PAUSE``, ``RESUME``, ``ACK``,
         *     ``COMPLETE``, ``FAIL`` and ``CANCEL`` are the robot reporting; the rest are the backend
         *     settling a reply, a silence or a robot that came back without the run.
         * @enum {string}
         */
        RunTrigger: "accept" | "reject" | "timeout" | "dispatch_unconfirmed" | "reconcile" | "pause_request" | "resume_request" | "cancel_request" | "ack" | "pause" | "resume" | "complete" | "fail" | "cancel";
        /**
         * RunView
         * @description A run with the stages it was dispatched with, frozen as they stood, and any failure.
         */
        RunView: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Mission Id
             * Format: uuid
             */
            mission_id: string;
            /** Robot Id */
            robot_id: string;
            status: components["schemas"]["RunStatus"];
            /**
             * Stages Digest
             * @description Content digest of what this run was told to do, ignoring stage ids and how a stage was produced. Two runs with the same digest drove the same ground.
             */
            stages_digest: string;
            origin: components["schemas"]["RunOriginView"];
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dispatched At */
            dispatched_at: string | null;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /** @description The robot's most recent report on this run; null before the first one. */
            last_report: components["schemas"]["LastReportView"] | null;
            /**
             * Updated At
             * Format: date-time
             * @description When the backend last changed this run: a status transition or a notes edit.
             */
            updated_at: string;
            /** Stages */
            stages: (components["schemas"]["NavigationStage"] | components["schemas"]["CoverageStage"])[];
            /**
             * Site Anchors
             * @description The frame of each site this run drove in, as it stood at dispatch, keyed by site id. Site-local waypoints are measured against these rather than against the site as it is now, so moving or deleting a site cannot move a run that already happened.
             */
            site_anchors?: {
                [key: string]: components["schemas"]["RunSiteAnchor"];
            } | null;
            /** Failure Errors */
            failure_errors?: components["schemas"]["MissionError"][] | null;
            /**
             * Transitions
             * @description The run's status changes so far, oldest first.
             */
            transitions?: components["schemas"]["RunTransitionView"][];
        };
        /**
         * Segment
         * @description One swath across a field, or the turn joining two of them.
         *
         *     The distinction is the reason coverage is a stage kind of its own. The ground under a swath is
         *     what gets worked, so a robot that took any convenient path between the same two endpoints would
         *     leave the strip beside it unworked; the ground under a turn is worked by nothing.
         */
        Segment: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "swath" | "turn";
            /**
             * Waypoints
             * @description The line to drive, in order. Two waypoints describe a straight run; more describe a curve, which cannot be recovered from its endpoints.
             */
            waypoints: (components["schemas"]["WGS84Waypoint"] | components["schemas"]["SiteLocalWaypoint"])[];
        };
        /** SiteCreate */
        SiteCreate: {
            /** Name */
            name: string;
            /** Anchor Lat */
            anchor_lat: number;
            /** Anchor Lon */
            anchor_lon: number;
            /** Anchor Heading Deg */
            anchor_heading_deg: number;
            /** Nav2 Map Ref */
            nav2_map_ref: string;
            outline?: components["schemas"]["Polygon"] | null;
            /** Description */
            description?: string | null;
        };
        /**
         * SiteLocalWaypoint
         * @description A waypoint expressed in a Site's local Cartesian frame.
         */
        SiteLocalWaypoint: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "site_local";
            /**
             * Site Id
             * Format: uuid
             * @description Identifies the Site whose local frame this waypoint uses.
             */
            site_id: string;
            /**
             * X
             * @description Meters along the site's local +x axis.
             */
            x: number;
            /**
             * Y
             * @description Meters along the site's local +y axis.
             */
            y: number;
            /**
             * Theta
             * @description Target robot heading in radians, CCW from the site's local +x axis.
             */
            theta?: number | null;
        };
        /** SiteUpdate */
        SiteUpdate: {
            /** Name */
            name?: string | null;
            /** Anchor Lat */
            anchor_lat?: number | null;
            /** Anchor Lon */
            anchor_lon?: number | null;
            /** Anchor Heading Deg */
            anchor_heading_deg?: number | null;
            /** Nav2 Map Ref */
            nav2_map_ref?: string | null;
            outline?: components["schemas"]["Polygon"] | null;
            /** Description */
            description?: string | null;
        };
        /** SiteView */
        SiteView: {
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Name */
            name: string;
            /** Anchor Lat */
            anchor_lat: number;
            /** Anchor Lon */
            anchor_lon: number;
            /** Anchor Heading Deg */
            anchor_heading_deg: number;
            /** Nav2 Map Ref */
            nav2_map_ref: string;
            outline: components["schemas"]["Polygon"] | null;
            /** Description */
            description: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * StageStateView
         * @description One stage's runtime state plus the errors attributed to it.
         */
        StageStateView: {
            /**
             * Stage Id
             * Format: uuid
             */
            stage_id: string;
            /** Stage Index */
            stage_index: number;
            status: components["schemas"]["StageStatus"];
            /** Progress */
            progress: number;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /** Result */
            result: {
                [key: string]: string;
            } | null;
            /** Errors */
            errors: components["schemas"]["MissionError"][];
            /**
             * Status Source
             * @description Who established the status: 'robot' when the robot reported it, 'backend' when the backend projected it because the run ended before the robot reported this stage.
             * @enum {string}
             */
            status_source: "robot" | "backend";
            /**
             * Parent Stage Id
             * @description Set on a cleanup stage: the stage whose cancel started it.
             */
            parent_stage_id?: string | null;
        };
        /**
         * StageStatus
         * @description Canonical per-stage status, covering both robot-reported and backend-resolved values.
         *
         *     A robot reports the stage a cancel interrupted as ``CANCELLED`` and the stages it never
         *     started as ``SKIPPED``; the backend assigns the same two when it closes a run the robot did
         *     not report to the end.
         * @enum {string}
         */
        StageStatus: "WAITING" | "INITIALIZING" | "RUNNING" | "PAUSED" | "FINISHED" | "FAILED" | "CANCELLED" | "SKIPPED";
        /** User */
        User: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WGS84Waypoint
         * @description A waypoint anchored in the WGS84 geographic frame.
         */
        WGS84Waypoint: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "wgs84";
            /**
             * Lat
             * @description Degrees latitude, WGS84.
             */
            lat: number;
            /**
             * Lon
             * @description Degrees longitude, WGS84.
             */
            lon: number;
            /**
             * Heading Deg
             * @description Target robot heading in degrees clockwise from true north (compass bearing), [0, 360).
             */
            heading_deg?: number | null;
        };
        /**
         * WaypointKind
         * @description A coordinate frame a waypoint can use; mirrors the Waypoint variants.
         * @enum {string}
         */
        WaypointKind: "wgs84" | "site_local";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_fields: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldView"][];
                };
            };
        };
    };
    create_field: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_field: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_field: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_field: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_robots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotView"][];
                };
            };
        };
    };
    get_robot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_missions: {
        parameters: {
            query?: {
                /** @description Filter to missions whose default robot is this robot id. */
                robot?: string | null;
                /** @description Filter to missions with exactly this name, matched case-insensitively. */
                name?: string | null;
                /** @description Also return archived missions. */
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_mission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mission_state: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_coverage_mission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionCoverageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionAssignBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unassign_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispatch_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MissionDispatchBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CancelBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunSelectBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunSelectBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mission_runs: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Only runs created before this instant; pages backwards. */
                before?: string | null;
            };
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    annotate_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunNotesPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_state: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteView"][];
                };
            };
        };
    };
    create_site: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_site: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_site: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_site: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
